login/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = "login"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('custom_redirect/', views.custom_redirect, name='custom_redirect'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('login:index')), name='logout'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('accounts/login/', views.CustomLoginView.as_view(), name='account_login'),
    path("report/", views.report, name="report"),
    path("report/submitted/", views.ReportDone.as_view(), name="report_done"),
    path('report/<int:report_id>/', views.report_detail, name='report_detail'),
    path('report/<int:report_id>/resolve/', views.resolve_report, name='resolve_report'),
    path('report/<int:report_id>/delete/', views.delete_report, name='delete_report'),
]

login/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models
# from .models import Report

class CustomUser(AbstractUser):
    USER_ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('regular', 'Regular'),
    )
    role = models.CharField(max_length=10, choices=USER_ROLE_CHOICES, default='regular')

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="customuser_set",
        related_query_name="customuser",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="customuser_set",
        related_query_name="customuser",
    )
class Report(models.Model):
    name_reported = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=20, default='New')
    resolved_notes = models.TextField(blank=True, null=True)
    reporter = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name_reported


class ReportFile(models.Model):
    report = models.ForeignKey(Report, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='report_files/')




    def __str__(self):
        return self.name_reported

login/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        exclude = ['reporter', 'published_date', 'status', 'resolved_notes']  #fields that do not show up when user is submitting a form, we do not want users to be able to set these values themselves

class ResolvedFeedbackForm(forms.Form):
    resolved_notes = forms.CharField(label='Resolution Details', widget=forms.Textarea, required=False)  #new form for site admin to submit text feedback

login/views.py
from allauth.account.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import RedirectView, TemplateView
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Case, When


from .models import Report, ReportFile
from .forms import ReportForm, ResolvedFeedbackForm

class IndexView(TemplateView):
    template_name = "index.html"

class LogoutRedirectView(RedirectView):
    url = reverse_lazy('index')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)

class CustomLoginView(LoginView):
    def get_success_url(self):
        return self.request.build_absolute_uri('/dashboard/')


def signout(request):
    logout(request)
    return redirect('/')

def is_site_admin(user):
    return user.is_authenticated and user.groups.filter(name='site_admin').exists()

@login_required
def custom_redirect(request):
    if request.user.is_superuser:
        return redirect('/admin/')
    if is_site_admin(request.user):
        return redirect('login:admin_dashboard')
    else:
        return redirect('login:user_dashboard')

@login_required
@user_passes_test(is_site_admin)
def admin_dashboard(request):
    all_reports = Report.objects.all().order_by(   #First sort by New, In Progress, Resolved
        Case(
            When(status='New', then=0),
            When(status='In Progress', then=1),
            When(status='Resolved', then=2),
            default=3
        ),
        '-published_date'       #Within the sorting of the 3 categories, sort by reverse chronological time
    )
    return render(request, 'admin_dashboard.html', {'user': request.user, 'all_reports': all_reports})

@login_required
def user_dashboard(request):
    # Logic for the user dashboard
    user_reports = Report.objects.filter(reporter=request.user).order_by( #logged-in user only gets access to their own past reports
        Case(   #Now ordering by status with resolved being first
            When(status='New', then=2),
            When(status='In Progress', then=1),
            When(status='Resolved', then=0),
            default=3
        ),
        '-published_date'  # Within the sorting of the 3 categories, sort by reverse chronological time
    )

    return render(request, 'user_dashboard.html', {'user': request.user, 'user_reports': user_reports})

@login_required
def user_profile(request):
    context = {
        'name': request.user.get_full_name(),
        'email': request.user.email,
    }
    return render(request, 'profile.html', context)

def report(request):  #method for user to submit a new whistleblowing report
    if request.method == 'POST':
        form = ReportForm(request.POST,  request.FILES)
        if form.is_valid():
            new_report = form.save(commit=False)
            if request.user.is_authenticated:
                new_report.reporter = request.user  #for logged-in user
            else:
                new_report.reporter = None    #anonymous users
            new_report.save()
            for file in request.FILES.getlist('file'):  # Make sure 'file' is the name attribute in your HTML form
                ReportFile.objects.create(report=new_report, file=file)

            return render(request, 'report_done.html') #redirect to new page after report is successfully submitted
    else:
        form = ReportForm()
    return render(request, 'report.html', {'form': form})

class ReportDone(generic.DetailView):
    template_name = "report_done.html"

class ReportResolved(generic.DetailView):
    template_name = "report_resolved.html"

@login_required
def report_detail(request, report_id):  #for displaying details of past reports for logged-in users and site admins
    report = get_object_or_404(Report, id=report_id)
    user_is_site_admin = is_site_admin(request.user)
    report_files = report.files.all()

    if user_is_site_admin:
        if report.status == 'New':    #when site admin opens report detail, then status changes from new to in progress
            report.status = 'In Progress'
            report.save()
        feedbackForm = handle_feedback(request, report)   #calls method for site admin to submit written text feedback about resolution
    else:
        feedbackForm = None     #if user is not site admin, they will not have the option to submit written feedback regarding the resolution
    return render(request, 'report_detail.html', {'report': report,  'report_files': report_files, 'form': feedbackForm, 'is_site_admin': user_is_site_admin})

@user_passes_test(is_site_admin)
def resolve_report(request, report_id):     #method used when site admin hits button to resolve the report
    report = get_object_or_404(Report, id=report_id)
    user_is_site_admin = is_site_admin(request.user)
    feedbackForm = handle_feedback(request, report)     #calls method for handling text feedback about resolution of report
    return render(request, 'report_detail.html', {'report': report, 'form': feedbackForm, 'is_site_admin': user_is_site_admin})

@user_passes_test(is_site_admin)
def handle_feedback(request, report):   #for handling written text feedback from site admin about resolving the report
    if request.method == 'POST':    #if site admin has hit the button to resolve a report/give feedback
        feedback_form = ResolvedFeedbackForm(request.POST)
        if feedback_form.is_valid():
            report.resolved_notes = feedback_form.cleaned_data['resolved_notes']    #gets text from feedback form and puts it in the report model
            report.status = 'Resolved'      #changes report status
            report.save()
    else:
        if report.resolved_notes: #if a site admin has already given feedback, then it will show up in the form for them to see (and they can still edit and re-submit the form)
            existing_data = {'resolved_notes': report.resolved_notes}
            feedback_form = ResolvedFeedbackForm(initial=existing_data) #form is initialized with the past submitted feedback
        else:
            feedback_form = ResolvedFeedbackForm()  #otherwise the form will show up as empty
    return feedback_form

@login_required
def delete_report(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    if request.method == 'POST':
        report.delete()
        return redirect('login:user_dashboard') 

login/templates/admin_dashboard.html
{% extends 'base.html' %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}
    <h2>Welcome Site Admin!</h2> <br>
  <p> Please review reports and if deemed medical malpractice, forward them to the appropriate authorities such as:</p>
  <ol>
    <li>bhp@dhp.virginia.gov</li>
    <li>Elliott.crigger@ama‐assn.org</li>
    <li>help@npdb.hrsa.gov</li>
  </ol>
  <table class="table">
    <thead>
      <tr>
        <th>Status</th>
        <th>Reporter</th>
        <th>Name Reported</th>
        <th>Date</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for report in all_reports %}
      <tr>
        <td>
          <span class="status-circle" style="background-color:
          {% if report.status == 'Resolved' %} green
          {% elif report.status == 'In Progress' %} yellow
          {% else %} red
          {% endif %};"></span>
          {{ report.status }}
        </td>
        <td>{% if report.reporter.username %}
            {{ report.reporter.username }}
          {% elif report.reporter.email %}
            {{ report.reporter.email }}
          {% else %}
            Anonymous
          {% endif %}</td>
        <td>{{ report.name_reported }}</td>
        <td>{{ report.published_date|date:"F j, Y, g:i a" }}</td>
        <td><a href="{% url 'login:report_detail' report.id %}">View Details</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <form method="post" action="{% url 'login:logout' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Logout</button>
  </form>
{% endblock %}

login/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MedWatch</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <style>
      body {
            font-family: 'Arial', sans-serif;
            color: #333;
            background-color: #f8f9fa;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        header {
            background: linear-gradient(to right, #0073e6, #ffa500);
            color: #fff;
            padding: 20px;
            margin-bottom: 20px;
        }
        footer {
            background-color: #f8f9fa;
            color: #555;
            padding: 20px 0;
            text-align: center;
            margin-top: auto;
            width: 100%;
        }
        .status-circle {
          width: 20px;
          height: 20px;
          border-radius: 50%;
          display: inline-block;
          margin-right: 10px;
        }
        .btn-login {
            background-color: #ffa500;
            color: #fff;
            border: none;
            padding: 10px 20px;
            margin-right: 10px;
            font-size: 16px;
            text-transform: uppercase;
        }
        .btn-report {
            background-color: #0073e6;
            color: #fff;
            border: none;
            padding: 10px 20px;
            margin-left: 10px;
            font-size: 16px;
            text-transform: uppercase;
        }
  </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>MedWatch</h1>
            <p>Ensuring transparency and integrity in healthcare</p>
        </div>
    </header>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
        <div class="container">
            <p>This system is a class project, not monitored, and no real information should be submitted. For more information, visit <a href="https://s24.cs3240.org/project.html">our website</a>.</p>
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

login/templates/index.html
{% extends 'base.html' %}
{% load static socialaccount %}

{% block title %}Home Page{% endblock %}

{% block content %}

<section class="container">
    <h2>Our Mission</h2>
    <p>To empower healthcare professionals to report misconduct, safety breaches, and unethical practices without fear of retaliation.</p>
</section>

<section class="container">
    <h2>Whistleblower Rights</h2>
    <ul>
        <li>Right to anonymity</li>
        <li>Right to protection from retaliation</li>
        <li>Right to have your report thoroughly investigated</li>
    </ul>
</section>

<section class="container">
<h2>Further Questions</h2>
<p>If you have further questions on what constitutes wrongful behavior, your responsibility to report misconduct, or UVA's whistleblowing policies, refer to the following resources.</p>
<ul>
    <li><a href="https://www.healthsystem.virginia.edu/codeofconduct/">UVA Health Compliance Code of Conduct</a></li>
    <li><a href="https://uvapolicy.virginia.edu/policy/RES-004">UVA Policy on Research Misconduct</a></li>
</ul>
</section>

<section class="container">
    <h2>How to Report</h2>
    <p>If you have witnessed or are aware of misconduct within your healthcare facility, take a stand and submit your report. Your identity can remain confidential.</p>
    <!-- Only show the following links if the user is not authenticated -->
    {% if not user.is_authenticated %}
        <div class="text-center">
            <a href="{% provider_login_url 'google' %}" class="btn btn-login">Login</a>
            <a href="{% url 'login:report' %}" class="btn btn-report">Submit a report anonymously</a>
        </div>
    {% endif %}
</section>

<!-- Only show the following section if the user is authenticated -->
{% if user.is_authenticated %}
    <section class="container">
        <p>Welcome back, {{ user.username }}.</p>
        <form action="{% url 'login:logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn btn-danger">
        </form>
    </section>
{% endif %}

{% endblock %}

login/templates/profile.html
{% extends 'base.html' %}
{% load static%}
{% block title %}User Profile{% endblock %}
{% block content %}
<head>
    <title>User Profile</title>
</head>
<body>
<h1>Welcome, {{ name }}</h1>
<p>Email: {{ email }}</p>
</body>
{% endblock %}

login/templates/report.html
{% extends 'base.html' %}
{% load static%}
{% block title %}Report Form{% endblock %}
{% block content %}

<style>
    .container {
        max-width: 100%; /* Adjust the width as needed */
    }
    form {
        margin: 20px;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    h2 {
        color: #0073e6; /* Blue */
        margin-bottom: 20px;
    }
    input[type="submit"] {
        background-color: #0073e6; /* Blue */
        color: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 16px;
        text-transform: uppercase;
        cursor: pointer;
    }
</style>

<div class="container">
    <form action="{% url 'login:report' %}" method="POST" enctype="multipart/form-data">
        <h2>Report</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="file" name="file" multiple>
        <input type="submit" />
    </form>

    {% if user.is_authenticated %}
        <a href="{% url 'login:user_dashboard' %}" class="btn btn-primary back-button">Back to My Reports</a>
    {% else %}
        <a href="{% url 'login:index' %}" class="btn btn-primary back-button">Back to Home</a>
    {% endif %}
</div>
{% endblock %}

login/templates/report_detail.html
{% extends 'base.html' %}
{% block title %}Report Details{% endblock %}
{% block content %}

<div class="container">
  <h1 class="mb-4">Report Details</h1>
  {% if report.reporter %}
    <p>Reported by: {{ report.reporter.get_full_name }}</p>
    <p>Email: {{ report.reporter.email }}</p>
  {% else %}
    <p>Reported by: Anonymous</p>
  {% endif %}

  <p>Date reported: {{ report.published_date }}</p>
  <p>Person reported: {{ report.name_reported }}</p>
  <p>Description: {{ report.description }}</p>

  <h3 class="mt-4">Attached Files:</h3>
  {% for file in report_files %}
    <p><a href="{{ file.file.url }}">{{ file.file.name }}</a></p>
  {% empty %}
    <p>No files attached.</p>
  {% endfor %}

  <br>
  <p>Status: {{ report.status }}</p>

  {% if is_site_admin %}
    <!-- page for site admin -->
    <form action="{% url 'login:resolve_report' report.id %}" method="post" class="mt-4">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Resolve Report</button>
    </form>
    <p><a href="{% url 'login:admin_dashboard' %}" class="btn btn-secondary mt-2">Back to Dashboard</a></p>
  {% else %}
    <!-- page for common user -->
    {% if report.status == 'Resolved' %}
      <p>Resolution Details: {{ report.resolved_notes }}</p>
    {% endif %}
    <form action="{% url 'login:delete_report' report.id %}" method="post" class="mt-4">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Delete Report</button>
    </form>
    <br>
    <p><a href="{% url 'login:user_dashboard' %}" class="btn btn-secondary mt-2">Back to Dashboard</a></p>
  {% endif %}
</div>

{% endblock %}

login/templates/report_done.html
{% extends 'base.html' %}
{% load static%}
{% block title %}Report Done{% endblock %}
{% block content %}
<style>
    .response-container {
        text-align: center;
        margin-bottom: 20px;
    }
    .response-container h3 {
        margin-top: 0;
        color: #0073e6;
    }
</style>

<div class="container response-container">
    <h3>Your response has been recorded</h3>
    {% if user.is_authenticated %}
        <p><a href="{% url 'login:user_dashboard' %}" class="btn btn-primary">Back to Dashboard</a></p>
    {% else %}
        <p><a href="{% url 'login:index' %}" class="btn btn-primary">Home</a></p>
    {% endif %}
</div>

{% endblock %}

login/templates/user_dashboard.html
{% extends 'base.html' %}
{% load static socialaccount %}
{% block title %}User Dashboard{% endblock %}
{% block content %}

<section class="container">
{% if user.first_name %}<h2>Welcome {{ user.first_name }}!</h2> {% else %}<h2>Welcome!</h2> {% endif %}
{% if user.email %} <p>Your account: {{ user.email }}</p>{% endif %}

<p>My Reports:</p>
<table class="table">
    <thead>
    <tr>
    <th>Status</th>
    <th>Name Reported</th>
    <th>Date</th>
    <th>Action</th>
    </tr>
    </thead>
<tbody>
    {% for report in user_reports %}
    <td>
        <span class="status-circle" style="background-color:
        {% if report.status == 'Resolved' %} green
        {% elif report.status == 'In Progress' %} yellow
        {% else %} red
        {% endif %};"></span>
        {{ report.status }}
    </td>
    <td>{{ report.name_reported }}</td>
    <td>{{ report.published_date|date:"F j, Y, g:i a" }}</td>
    <td><a href="{% url 'login:report_detail' report.id %}">View Details</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>
<br>
    <form action="{% url 'login:logout' %}" method="post">
        {% csrf_token %}
        <a href="{% url 'login:report' %}" class="btn btn-report">New report</a>
        <button type="submit" class="btn btn-danger">Logout</button>
    </form>
</section>
{% endblock %}